# Generated by Django 4.2.3 on 2024-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(unique=True)),
                ("view_name", models.CharField()),
                ("app_name", models.CharField()),
            ],
        ),
    ]
