# Generated by Django 4.2.3 on 2024-03-05 21:36

from django.db import migrations
from todo.views import TODOBaseView, TODOGenericView


def migrate_forwards(apps, schema_editor):
    AppLabel = apps.get_model("dashboard", "AppLabel")
    AppLabel.objects.create(
        label="TODO",
        view_name=TODOBaseView.view_name,
        app_name=TODOGenericView.app_name,
    )


def migrate_backwards(apps, schema_editor):
    AppLabel = apps.get_model("dashboard", "AppLabel")
    AppLabel.objects.filter(label="TODO").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_add_app_label_model"),
    ]

    operations = [migrations.RunPython(migrate_forwards, migrate_backwards)]
