# Generated by Django 4.2.3 on 2024-03-05 21:36

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    # AppLabel = apps.get_model("dashboard", "AppLabel")

    pass


def migrate_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_add_app_label_model"),
    ]

    operations = []
