# Generated by Django 4.2.3 on 2024-03-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0002_add_simple_history_to_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="todo.taskcategory")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tasks", models.ManyToManyField(to="todo.task")),
            ],
        ),
    ]
