# Generated by Django 4.2.3 on 2023-10-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_add_user_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="morty.jpg", null=True, upload_to="avatars/"
            ),
        ),
    ]
