# Generated by Django 4.2.3 on 2023-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_avatar_model_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
