# Generated by Django 4.2.3 on 2024-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_default_users_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boostedgroup',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='boostedgroup',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
